add read only mode feature
ualbertalib/jupiter pull request #1862
Opened 2020-09-09 16:33 UTC by ConnorSheremeta

#1838

Tests pending as I cannot get them to stop flapping for the life of me. Hoping it's something that might be able to be picked up from a review.

2020-09-09 17:07 UTC, murny commented on db/migrate/20200831181118_create_read_only_modes.rb
> +      t.boolean :enabled
Should force this as `null: false` and `default: false`?

2020-09-09 17:11 UTC, murny commented on app/views/application/_navbar.html.erb
> +            <%= link_to t('.links.login'), '/auth/saml', class: 'nav-item nav-link text-nowrap', method: :post if ReadOnlyMode.disabled? %>
Are you still able to login with dev mode (below) if ReadOnlyMode is disabled? If not, then we should wrap both of these login buttons in this if condition

2020-09-09 17:13 UTC, murny commented on test/controllers/sessions_controller_test.rb
> -  test 'should not log in from a saml account that was changed to system' do
Is this no longer valid? You can login from saml with system user now?

2020-09-09 17:14 UTC, murny commented on app/models/user.rb
> +  validates_uniqueness_of :system, if: :system
I would say we use what rubocop wants? Instead of disabling it

```
# bad
validates_uniqueness_of :foo

# good 
validates :foo, uniqueness: true
```

2020-09-09 17:16 UTC, murny commented on app/models/read_only_mode.rb
> +  validate :only_one_record_exists, on: :create
Should throw a quick validation on the enabled boolean field. e.g:

```

validates : enabled, inclusion: { in: [true, false] }

```

2020-09-09 17:18 UTC, murny commented on config/locales/en.yml
> +              only_one_record_exists: 'Only one read_only_mode record may exist'
Minor but since we talking about the model here, should maybe be `ReadOnlyMode` instead of `read_only_mode`

2020-09-09 21:21 UTC, murny commented on app/views/application/_navbar.html.erb
> +              <%= link_to t('.links.login_as_dev'), '/auth/developer', class: 'nav-item nav-link text-nowrap', method: :post if ReadOnlyMode.disabled? %>
Minor but I'd throw the if logic around the entire html. Why? Cause this creates extra markup when false.

E.g when ReadOnlyMode is enabled, then this markup still gets rendered in the HTML:
```
<li role="presentation" class="nav-item">
</li>
<li role="presentation" class="nav-item">
</li>
```

If you surrounded this markup with an if block instead:

```
<% if ReadOnlyMode.disabled? %>
  ...contents
<% end %>
```
Then no markup gets rendered when ReadOnlyMode is enabled.

2020-09-09 21:23 UTC, murny commented on app/models/read_only_mode.rb
> +class ReadOnlyMode < ApplicationRecord
Since we adding a new model can we add a new model test for this class?

And just check some simple things like...can we create more then one record? can we create a record without setting enabled? Does our class level methods work properly (enable/disable/etc) etc

2020-09-09 21:24 UTC, murny requested changes
Looks really good. Just would like to see a model test for the new ReadOnlyMode model 👍. Then I'll approve 🥇

2020-09-09 21:45 UTC, mbarnett requested changes

2020-09-09 21:45 UTC, mbarnett commented on app/controllers/application_controller.rb
> +    return if ReadOnlyMode.enabled?
I'm going to suggest we create a method in ApplicationController to wrap `ReadOnlyMode.enabled?` and hoist the `Rails.cache.fetch('read_only_mode.first.enabled', expires_in: 1.minute) do` caching policy up into the method in ApplicationController, rather than keeping it in the model.

There's a couple of reasons for this: one I'll get to below, but the other one is just that caching feels like application policy and what you want for the web application isn't necessarily what you want for other use-cases, like rake tasks (like, if we wanted a task to check the status, we'd want it to report the real-time state, not the cached value. that's harder if the model itself is hiding the caching)

2020-09-09 21:45 UTC, mbarnett commented on app/views/application/_navbar.html.erb
> +            <%= link_to t('.links.login'), '/auth/saml', class: 'nav-item nav-link text-nowrap', method: :post if ReadOnlyMode.disabled? %>
This is the other reason to wrap this call in a method in ApplicationController: Views shouldn't talk directly to models, we want a method in the controller layer in between to act as a "fire-break" to keep them from getting to familiar with one another. It helps keep things more cleanly separated, which makes any refactoring down the road a lot easier.

2020-09-09 21:45 UTC, mbarnett commented on app/models/read_only_mode.rb
> +    Announcement.where(user: User.system_user.id).destroy_all
Because we have all of the scopes declared properly, you can just use the ActiveRecord join helpers! `User.system_user.announcements`

2020-09-09 21:45 UTC, mbarnett commented on app/models/read_only_mode.rb
> +  end
@murny want to get your thoughts on this, too: 

We have some fairly tight coordination between 2 (3, if you count the magic system user) different models here, and depending on who you ask, this tight inter-model coupling of state is a bad idea. Options would be to just let the models touch each other like this, move to something like the old Observer system, or just pull `enable` and `disable` up into a Service and let it handle the coordination? So you could check values on the model, but actually changing it requires using the service?

2020-09-09 22:02 UTC, murny commented on app/models/read_only_mode.rb
> +  end
Current code isn't bad by any means (but if we add more things to this Model in the future, then it could become troubling). But I like where your going with this. I'd probably lean towards a service object as well instead of these Class level methods that are touching multiple models. This makes our ReadOnlyMode model super simple and straightforward.

 This logic is perfect candidate for a Service object (Ruby module which encapsulates the logic for completing an action). A simple ReadOnlyService that completes the action of turning on or off Read Only Mode for Jupiter 👍

2020-09-10 07:01 UTC, mbarnett commented
Forgot to mention: remember this needs to be opened against master, too, because we need it in prod for the deployment.

2020-09-14 16:18 UTC, murny commented on test/services/read_only_service_test.rb
> +  include ActiveJob::TestHelper
Probably not needed? Doesn't look like your checking for jobs being queued/etc in the tests

2020-09-14 16:19 UTC, murny submitted a review, later dismissed
Very nice work on service and adding tests 👏.

Just a small extra include I saw in your service tests. Otherwise looks good 👍

2020-09-15 00:34 UTC, murny approved these changes

2020-09-29 20:38 UTC, mbarnett approved these changes

2020-09-29 21:24 UTC, merged