Implement doi resetting for admins
ualbertalib/jupiter pull request #1891
Opened 2020-09-25 17:26 UTC by ConnorSheremeta

#1739

2020-09-25 17:50 UTC, murny commented on config/routes.rb
> +  get '/admin/reset_doi/:id', to: 'admin/doiable#reset_doi', as: '/admin/reset_doi'
Couple things here. First a `get` request is suppose to be `idempotent` (same operation applied multiple times yields the same result). This is not idempotent as you are changing data. Also you have to remember how a browser operates. Why is chrome so fast? It thinks ahead. It will click on links before you even get to them. Having this link on the page that is a get request, guess what? Chrome will click on it for you even if you have no intention of issuing a request for resetting the DOI. This is a problem!

Second, we should preferably get nested under admin namespace or you should add the `constraints: AdminConstraint.new` to this. So this only gets exposed and gives responses to admin users.

Easy way to get it nested under admin namespace is to be more RESTful.

```
  resources :doi, only: [] do
    match do
      post :reset
    end
  end
```

Or is reset much different then a create? If it is, we can go full REST just do this:
`resources :doi, only: [:create]`

2020-09-25 22:45 UTC, murny commented on app/views/items/_admin_sidebar.html.erb
> +          <%= link_to(t('.reset_doi'), admin_reset_doi_path(@item),
Should we throw a confirmation dialog on this too? Just to add some caution to it?

Like "Do you want to proceed to reset the DOI? Yes / No"

```ruby
<%= link_to(t('.reset_doi'), admin_reset_doi_path(@item),
class: 'btn btn-outline-primary',
data: { confirm: t('.are_you_sure_you_want_to_reset') }) %>
```

2020-09-25 23:06 UTC, mbarnett requested changes

2020-09-25 23:06 UTC, mbarnett commented on app/helpers/items_helper.rb
> +    aasm_not_available = item.aasm_state == 'not_available'
AASM gives you a bunch of helper methods for the declared states, eg) `item.not_available?`

2020-09-25 23:06 UTC, mbarnett commented on config/routes.rb
> +  get '/admin/reset_doi/:id', to: 'admin/doiable#reset_doi', as: '/admin/reset_doi'
On top of Shane's good point, I'm thinking this route and the corresponding method would probably make more sense under `Admin::ItemsController`? We're kind of creating a single-purpose controller to handle a change to one small part of a model that already has its own controller – it would make more sense to me to fold it into the main admin controller for these models.

2020-10-01 03:59 UTC, murny commented on test/integration/doi_reset_test.rb
> +    # A community with two collections
We don't need all this setup here? Should be able replace all this setup from Line 8 to Line 29 with just 

`@item = items(:fancy)` 

Should give you the exact same results (especially since we never access @community/@collection1/@collection2 in any of the test code)

2020-10-01 04:03 UTC, murny commented on config/routes.rb
> +    patch '/reset_doi/:id', to: 'items#reset_doi', as: '/reset_doi'
Minor but its probably easier to maintain if we keep this route with the rest of the admin `items` routes on Line 68:

`resources :items, only: [:index, :destroy]`

Can just become:

```
    resources :items, only: [:index, :destroy] do
       member do
         patch :reset_doi
       end
    end

```

which gives you the exact same kind of functionality as your code here. There will be slight differences but it's more RESTful.

For example the route name will now be `reset_doi_admin_items` instead of `admin_reset_doi` and the url will be `admin/items/:id/reset_doi` instead of `admin/reset_doi/:id`

2020-10-01 04:11 UTC, murny commented on test/integration/doi_reset_test.rb
> +class DoiResetTest < ActionDispatch::IntegrationTest
Nice work on this test, looks good 👍. 

Curious if we can get some more test coverage for our new `reset_doi` action at the controller level? Essentially add a test in Admin::ItemsControllerTest that probably just sends a patch to `reset_doi` acton, check if a DOICreateJob gets enqueued in our job queue, and finally checks if we are successfully redirected back

Other than these 3 minor things, PR is looking really good 🎉

2020-10-06 17:49 UTC, ConnorSheremeta commented on test/integration/doi_reset_test.rb
> +    # A community with two collections
I created the item in the setup block because it lets the test check that the 'Reset DOI' button is not present within the first minute of the item's creation. I just realised that I can still use fixtures and test that, just need to do some time travelling.

2020-10-06 18:51 UTC, ConnorSheremeta commented on test/integration/doi_reset_test.rb
> +class DoiResetTest < ActionDispatch::IntegrationTest
We have[ DOI minting disabled in test](https://github.com/ualbertalib/jupiter/blob/d7d5fe5ea66a28e628e9731d71cf9788c2867afc/config/secrets.yml#L24).

Do either of you know if enabling this (just for the test env) will have any negative repercussions? Should I try to enable it just for this particular test? @mbarnett @murny

2020-10-06 18:57 UTC, murny commented on test/integration/doi_reset_test.rb
> +class DoiResetTest < ActionDispatch::IntegrationTest
Hmm, it shouldn't impact things as we don't run a real ActiveJob queue in testing (its just a mocked array). And I assume all of our DOI minting stuff runs as background jobs. So we should be safe turning it on in testing?

Worse case we can just leave it as is, and just leave out the `check if DOICreateJob gets enqueued in our job queue` part of the test (really just checking if the controller action returns a successful response code (redirect)).

I'll let Matt decide 😆

2020-10-07 19:51 UTC, closed without merging