#1800: Add solr highlight for description/abstract fields on search r…
ualbertalib/jupiter pull request #1895
Opened 2020-09-27 22:01 UTC by murny

#1800 

Adds solr highlighting to item description/thesis abstract fields on search results (for search, profile and collection search pages)

Highlighting in action:

Search page:
![image](https://user-images.githubusercontent.com/1930474/94376840-627a8800-00da-11eb-92db-397379571f20.png)
![image](https://user-images.githubusercontent.com/1930474/94376774-f26c0200-00d9-11eb-991d-9cb37dc13964.png)

Profile page:
![image](https://user-images.githubusercontent.com/1930474/94376760-dbc5ab00-00d9-11eb-9a7c-42d6ec186ee2.png)

Collection show page:
![image](https://user-images.githubusercontent.com/1930474/94376779-00ba1e00-00da-11eb-9597-df3e93d3630e.png)

2020-09-27 22:03 UTC, murny commented on app/services/user_search_service.rb
> -    raise ArgumentError, 'Must supply both a key and value' if @base_restriction_key.present? && @value.blank?
Oops this is a bug. `@base_restriction_key` and `@value` will always be blank here as we don't define these until later. We want the arguments that have been passed in instead (e.g `base_restriction_key` and `value`)

2020-09-27 22:05 UTC, murny commented on app/services/user_search_service.rb
> -                 search_models: [Item, Thesis], params: nil)
Params must be present here, we shouldn't default to nil. We take these params and pass it into our `search_params` function below:

`@search_params = search_params(params)`

`search_params` will crash if `nil` is given for the params value.

So let's make params be a required argument (like current_user)

2020-09-28 17:18 UTC, mbarnett requested changes
(I haven't looked at this in depth yet, I'm just blocking the merge so that we don't accidentally import this into the about-to-become-master branch before we tag our final version of new prod. Will review in a bit)

2020-09-28 23:32 UTC, mbarnett reviewed
Overall I really like this!

Added some thoughts on how we could tweak the API to be a bit DRYer, and make it opt-in because current ERA controllers won't want to leverage this immediately.

Will give a bit more thought to the results rendering API tomorrow but this seems good to start with.

2020-09-28 23:32 UTC, mbarnett commented on app/controllers/collections_controller.rb
> +        Thesis.solr_exporter_class.solr_name_for(:abstract, role: :search)
Should we expand the DSL around Solr to let this be declared in the exporter rather than in the controller? Might centralize this knowledge in a SPOT rather than risk bugs where we add it in one context but not another?

I'm thinking something like https://github.com/ualbertalib/jupiter/blob/bcc71dadee525771cd36754f3b4d42f1765e882a/app/models/exporters/solr/item_exporter.rb#L65

maybe 

```ruby
full_text_searchable :description
```

?

Then we could change the API for SearchService a bit to just take a `fulltext: true` argument and default it to `false`, and then not use it in the current controllers like here, but opt into it in the digitization controller?

2020-09-29 18:40 UTC, mbarnett reviewed
Added some thoughts on how we could make some changes to the results API to DRY up the views having to know the field that was fulltext indexed/searched, and how wrapping the raw RSolr result would drop a bunch of logic out of the views

2020-09-29 18:40 UTC, mbarnett commented on app/models/jupiter_core/solr_services/deferred_faceted_solr_query.rb
> +    @highlights || {}
I'm thinking we should pre-bake the results here rather than returning the raw structure we get from RSolr and processing it in the helper.

What if we added something like an `each_with_fulltext_results` method?

Then this: https://github.com/ualbertalib/jupiter/blob/bcc71dadee525771cd36754f3b4d42f1765e882a/app/views/application/_results.html.erb#L81-L85

becomes something like
```ruby
<% results. each_with_fulltext_results do |result, fulltext_hits| %>
  <li class="list-group-item list-group-item-action">
    <%= render result, highlights: fulltext_hits %>
  </li>
<% end %>
```

and the implementation looks something like:

```ruby
def each_with_fulltext_results
  each do |obj|
    fulltext_solr_field = obj.solr_exporter_class.fulltext_searchable_solr_field
    fulltext_hits = @highlights[obj.id][fulltext_solr_field].map { |hit|  new FulltextResult(highlight_text: hit)}
    yield obj, fulltext_hits
  end
end
```

Baking it like this eliminates the need for the view to hardcode a fieldname that matches the search configuration elsewhere, and wrapping the results in a little utility class will let us simplify the views a lot (see comment there)

2020-09-29 18:40 UTC, mbarnett commented on app/views/application/_item.html.erb
> +      <% end %>
if we assume that we changed the API and wrapped the matches in a little utility class, `highlights` is now an array of instances of the utility class, and you can replace these 9 lines with

```erb
<p>
<%= render highlights || jupiter_truncate item.description %>
</p>
```

and add a little `_fulltext_result.html.erb` partial to render its contents. Rails' collection partial rendering returns nil if the collection is empty, making the fallback easy.

tl;dr basically prebaking the results and wrapping them in a custom class drops a lot of logic out of the views.

2020-09-29 18:52 UTC, murny commented on app/controllers/collections_controller.rb
> +        Thesis.solr_exporter_class.solr_name_for(:abstract, role: :search)
Yeah I would love to do this 🎉 . 

Sunspot leaves it like I did at the search level. 

But popular elasticsearch gems (like SearchKick) does exactly what your proposing. See https://github.com/ankane/searchkick#highlight for an example.  On the model level they denote what fields are highlight-able. Then when they search they pass in a `highlight: true` flag and can get the results with `results.with_highlights.each` (which is basically what your proposing here and your view cleanup proposal below)

I just might need to bug you on best way to do this? Like we set `full_text_searchable :description` and that becomes exposed in  `app/models/jupiter_core/search.rb` 🤔 . I think I'm getting it, just need to spend some time fleshing this out

2020-09-29 18:54 UTC, murny commented on app/models/jupiter_core/solr_services/deferred_faceted_solr_query.rb
> +    @highlights || {}
Yeah I like where you going with this 💯 . Much cleaner (and much similar to Searchkick as noted above). Will see what I can do 👍

2020-09-29 18:54 UTC, mbarnett commented on app/controllers/collections_controller.rb
> +        Thesis.solr_exporter_class.solr_name_for(:abstract, role: :search)
I've got some time today, I can add this and PR it to your branch

2020-09-29 18:58 UTC, murny commented on app/controllers/collections_controller.rb
> +        Thesis.solr_exporter_class.solr_name_for(:abstract, role: :search)
Sure, that be great! Just enough to get me started 👍

2020-10-07 19:51 UTC, closed without merging