Solr highlighting
ualbertalib/jupiter pull request #1929
Opened 2020-10-07 21:04 UTC by murny

See https://github.com/ualbertalib/jupiter/pull/1895 for original PR

#1800 

Adds solr highlighting to item description/thesis abstract fields on search results (for search, profile and collection search pages)

Highlighting in action:

Search page:
![image](https://user-images.githubusercontent.com/1930474/94376840-627a8800-00da-11eb-92db-397379571f20.png)
![image](https://user-images.githubusercontent.com/1930474/94376774-f26c0200-00d9-11eb-991d-9cb37dc13964.png)

Profile page:
![image](https://user-images.githubusercontent.com/1930474/94376760-dbc5ab00-00d9-11eb-9a7c-42d6ec186ee2.png)

Collection show page:
![image](https://user-images.githubusercontent.com/1930474/94376779-00ba1e00-00da-11eb-9597-df3e93d3630e.png)

2020-10-07 22:43 UTC, mbarnett requested changes
![Great Job](https://i.giphy.com/media/KWRQl6Y83aUptxIYu7/giphy.gif)

Looks really really good!

Only needed change is that we disable it on all of the current controllers, as we're not looking to roll this out on ERA for now, just leverage it in the Digitization work.

2020-10-07 22:43 UTC, mbarnett commented on app/controllers/collections_controller.rb
> +      fulltext: true
Should be false for all current controllers so-as to maintain the current search experience on ERA for the time being. We'll want to start using this on the Digitization controllers.

2020-10-09 20:51 UTC, murny commented on app/controllers/collections_controller.rb
> +      fulltext: true
Makes sense 👍. This now has been updated.

2020-10-21 20:34 UTC, mbarnett approved these changes

2020-10-21 20:35 UTC, merged