Give proper response when solr 400s
ualbertalib/jupiter pull request #2088
Opened 2021-01-13 22:05 UTC by ConnorSheremeta

#2086

When solr gives a 400 we give a 500, we want to give a 400 error code and message.

2021-01-13 22:47 UTC, murny reviewed
Looks pretty good. Just some small feedback

2021-01-13 22:47 UTC, murny commented on app/controllers/application_controller.rb
> +  def render_400(exception = nil)
400 is a generic error (bad request was given). So I would maybe propose we either keep this generic or make this more specific as a result. 

To keep it generic, then Instead of hardcoding the "error message" as "Looks like there is an issue with your search query!" on the page you could do something smarter here like pass error message into the view by setting a instance variable on the controller.

To keep it specific, then rename this to be only for solr bad requests, so rename this method and the 400.html page to be `render_solr_bad_request` and `solr_bad_request.html` or something

2021-01-13 22:47 UTC, murny commented on app/controllers/application_controller.rb
> +        render file: Rails.root.join('public/400.html'), layout: false, status: :bad_request
Might be out of scope but alternatively, it be really nice if we can just show them the search page again with the "error" highlighted or allow them to recover themselves. Similar to what we do for a bad form submission.

So instead of showing them a generic static 4xx.html  like so which may confuse users:
![image](https://user-images.githubusercontent.com/1930474/104517727-cce50480-55b3-11eb-9bf1-70760a2601ee.png)

We just re-render the search page again with an error. This way they can enter a new search query again (similar to what we do when no results are found). Much better UX this way
![image](https://user-images.githubusercontent.com/1930474/104517983-39f89a00-55b4-11eb-9dcc-097eb243080b.png)

2021-01-13 22:47 UTC, murny commented on test/integration/bad_solr_request_test.rb
> +    get "#{root_path}/search?facets[all_subjects_sim][]=Antimicrobial&facets[all_subjects_sim][]=%22blown-pack%22"
Could we try to convert these URLs to use the rails link helpers instead of string concatenation. Think it's easier to read if its just arguments in a method vs a a 3 line long string. Also not sure if this will work in the future once we have subdomains  enabled (link helpers take care of subdomains for us by looking up the subdomain in the routes file).

Might be able to just do the following (needs testing as syntax might not be perfect):

```
get search_url, params: { search: 'test', facets: [all_subjects_sim: ["Antimicrobial", "blown-pack"]], sort: 'title'}
```
etc.

2021-01-13 22:51 UTC, mbarnett commented on app/controllers/application_controller.rb
> +        render file: Rails.root.join('public/400.html'), layout: false, status: :bad_request
Do you have a good suggestion on how to kick them back to the general search page without adding a special action or some special case code to the search action, but still make sure we are sending a 400 in the header?

(The backstory here is that Bing has a bad set of URLs for searches from somewhere or other that it keeps hitting over and over again, I assume because it just thinks "hmm 500 better try again later", and it's causing a bunch of noise in Rollbar for no benefit – I'm hoping that seeing the 400 will convince it to drop them from the index finally)

2021-01-13 22:56 UTC, murny commented on app/controllers/application_controller.rb
> +        render file: Rails.root.join('public/400.html'), layout: false, status: :bad_request
If thats the backstory then this may be fine. As its a bot hitting us, or a user coming from a search engine, and not a user who typed in a search term and got this 400.html page which would be a bit confusing.

No suggestion but you would probably be right. In order to kick them back to the general search page, we would need to change some code (probably simplest is to pass in a `@error_message` that if present, renders it out instead of the normal search results or something). So is this worth it? Not sure. If it's just outside traffic/bots then this is fine 🤔

2021-01-13 22:58 UTC, mbarnett commented on app/controllers/application_controller.rb
> +        render file: Rails.root.join('public/400.html'), layout: false, status: :bad_request
Yeah I haven't really seen much evidence this is impacting people, other than the occasional curious person messing around with the query params

2021-01-13 23:02 UTC, murny commented on app/controllers/application_controller.rb
> +        render file: Rails.root.join('public/400.html'), layout: false, status: :bad_request
Let's leave it as is then 👍

2021-01-14 22:22 UTC, murny commented on test/integration/solr_bad_request_test.rb
> +    get search_url, params: { facets: { all_subjects_sim: ['Antimicrobial', '"blown-pack"'] } }
Much nicer 👍

2021-01-14 22:23 UTC, murny approved these changes
Looks good to me 👍

2021-01-14 22:30 UTC, murny commented on app/models/jupiter_core/search.rb
> +        raise JupiterCore::SolrBadRequestError if e.response[:status] == 400
Does `raise` break the execution here? or does it fall through and hit the second raise and you get a double raise 🤔 ?

Not sure if this is a problem but you could restructure the `if` condition here so this would never happen 

```
if e.response[:status] == 400
  raise JupiterCore::SolrBadRequestError
else
  raise
end
```

2021-01-14 22:33 UTC, mbarnett commented on app/models/jupiter_core/search.rb
> +        raise JupiterCore::SolrBadRequestError if e.response[:status] == 400
It _should_ break the execution, unless I'm crazy.

I don't think you can double raise in Ruby. Are you thinking of a double render?

2021-01-14 22:34 UTC, murny commented on app/models/jupiter_core/search.rb
> +        raise JupiterCore::SolrBadRequestError if e.response[:status] == 400
Yeah I think this is fine, so feel free to ignore me 😆

2021-04-23 20:27 UTC, mbarnett requested changes
Just one quick change I'd like to see to the naming to make this a more generic solution to other 400 problems in the future.

2021-04-23 20:27 UTC, mbarnett commented on app/controllers/application_controller.rb
> +  def render_solr_bad_request(exception = nil)
Ok, my one and only request here is that, since what we're doing here is 400ing, we make this method name, and the file name, more generically about that status (so that if there are other reasons we also want to return a 400 in the future, we use this same code path, rather than making it seem specific to Solr).

So just like we have `render_404` and `public/404.html` this can just be the 400 version of that method and file.

2021-04-27 21:08 UTC, mbarnett approved these changes

2021-04-27 21:14 UTC, merged