Pgj/2010 digitization books model folk fest
ualbertalib/jupiter pull request #2089
Opened 2021-01-14 00:14 UTC by pgwillia

## Context

The first set of digitization content will be the Folk Fest Programs. This set was chosen because it is small (there are 36) and well described. Before we can ingest them we need to do some modelling.

Related to #2010

## What's New

- added attributes to Digitization::Book model and their rdf annotations
- added validations for the attributes
- added several controlled vocabularies and relevant FolkFest values
- added `edtf` to help parse and validate Extended Date/Time Format

2021-01-14 00:26 UTC, pgwillia reviewed
Would love some feedback.  It's not perfect as I've pointed out but probably good enough.

2021-01-14 00:26 UTC, pgwillia commented on Gemfile
> +gem 'edtf', '~> 3.0', '>= 3.0.6' # parsing Extended Date/Time Format
Added this gem to do the heavy lifting of validating a number of different formats for dates that are less precise (decades, seasons, etc) than Date.

2021-01-14 00:26 UTC, pgwillia commented on app/validators/edtf_validator.rb
> +        unless Date.edtf(date)
This is the one place `edtf` gem is used.

2021-01-14 00:26 UTC, pgwillia commented on test/controllers/admin/theses/draft_controller_test.rb
> +    assert_equal (Date.current + 1.year).to_datetime, draft_thesis.embargo_end_date
A side effect of using the `edtf` gem is that the default format for Date objects is less precise that the `embargo_end_date` `datetime` type.

2021-01-14 00:26 UTC, pgwillia commented on config/controlled_vocabularies/digitization_subject.yml
> +digitization_subject:
I'm not sure if this approach is going to be able to scale.  The `digitization_subject` vocabulary is used by `geographic_subject` and `topical_subject`.  May be overlap with `place_of_publication` and `publisher`.

2021-01-14 00:26 UTC, pgwillia commented on db/migrate/20201204210653_add_folk_fest_attributes_to_digitization_book.rb
> +      t.extent has_predicate: ::RDF::Vocab::RDAU['/P60550']
This vocabulary is a bit different from others we've worked with. The uri is `http://rdaregistry.info/Elements/u/P60550` but the property is `rdau:extent.en`.  I think the design of it is to be language agnostic but it ends up being pretty opaque.

2021-01-14 00:26 UTC, pgwillia commented on db/seeds.rb
> +  Digitization::Book.create(peel_id: rand(1..3400), part_number: rand(1..100),
There's probably more variation that I could do here.  There aren't many terms in the controlled vocabulary to iterate on yet.  The biggest improvements that could be made here is to 

- leave blank some of the optional fields
- have more values in the 0+ fields
- choose 1 or more of the subjects

2021-01-18 22:18 UTC, mbarnett requested changes
(just putting a block on the merge to prevent any accidental merging until I've had a chance to fully think through everything)

2021-01-26 00:22 UTC, mbarnett requested changes
There's a couple of small things worth changing I've noted – the TODOs I suggest may even be worth trying to tackle now rather than letting the number of occurrences of the same pattern grow?

Bigger concern I'm wrestling with is just how many JSON columns we're already looking at and whether or not some of that might be better modelled in another way – either as singular values if their multiplicity is more "speculative", or as more of a relational join table design if we know they're not necessarily freeform values but coming from a limited vocab we could just load up in the DB. Some of this might be worth you and I discussing so that we can put together a solid idea of how we want to tackle this going forward.

2021-01-26 00:22 UTC, mbarnett commented on db/migrate/20201204210653_add_folk_fest_attributes_to_digitization_book.rb
> +    end
We might need to be a bit more liberal in how we approach translating metadata's models – specifically, where possible we want to bias towards making things singular and only emitting multival values when translating back for them, because both the query language and performance implications of having a ton of JSON columns aren't great or will end up being annoying to work with. 

We can certainly use them where we have to, but we should be _sure_ we have to for the data we actually have and that we're not going to be wanting to construct a lot of queries against the data.

So just looking at this and glancing at the triples, date Issued seems to be purely single valued in the data we have from glancing at the triples, so let's run with that. Something like Genre we might consider implementing as a join table if there's a fixed schema of values we'll only ever be referencing (ie. if we can know and preload them all before hand – if I'm looking at the correct triple it looks like that may be the case, but unsure how well that generalizes to other books), otherwise we can go this route. Place of publication doesn't make sense to me that that would routinely have multiple values, but possibly some other data might (and obviously we'll have to reconsider this as more data rolls in over time)...

Just something to think about, because it's very easy for us to go too hard down the JSON rabbit hole and make things excessively hard to write queries against later.

2021-01-26 00:22 UTC, mbarnett commented on db/migrate/20201204210653_add_folk_fest_attributes_to_digitization_book.rb
> +      t.extent has_predicate: ::RDF::Vocab::RDAU['/P60550']
Woof, yeah. This is worth putting some thought into how we could give this some kind of meaningful name, because as it stands this is incomprehensible, and I don't want to go the route of having these opaque, meaningless codes scattered throughout the code base.

 I see it as kind of the difference between "I should be able to understand what something is by it's name" and kind of the more 'Library-y' approach of a Discovery or similar, which has a bunch of Librarian acronyms and location codes embedded in the code that make onboarding really really hard?

2021-01-26 17:33 UTC, pgwillia commented on db/migrate/20201204210653_add_folk_fest_attributes_to_digitization_book.rb
> +    end
I was going on the observation that everywhere in ERA that required an array that json was used.  Perhaps these should be a different type?  Arrays of strings?

Maybe I should set up a discussion with the metadata team (Sharon?) about the assumptions that we're making.  I'm sure that they've looked at the data when creating their models.  They might know if the assumptions we're thinking of making will play out.

2021-01-26 17:38 UTC, mbarnett commented on db/migrate/20201204210653_add_folk_fest_attributes_to_digitization_book.rb
> +    end
Yeah, if we need an array, JSON arrays are the way to go unless the things we're trying to have multiple values of are fixed enough that a Join Table might be more natural. So authors are completely freeform and infinite and bad for join tables, but genres might be.

Let's meet and figure out the approach we think we want to take and then develop questions we might have for Metadata based on the outcome of that.

2021-02-25 00:01 UTC, pgwillia commented on test/fixtures/digitization/books.yml
> +  resource_type: <%= CONTROLLED_VOCABULARIES[:digitization][:resource_type].txt %>
@mbarnett I was just thinking that we wouldn't be able to reason like this if there's a direct <label>: <uri> mapping.

2021-02-25 00:03 UTC, mbarnett commented on test/fixtures/digitization/books.yml
> +  resource_type: <%= CONTROLLED_VOCABULARIES[:digitization][:resource_type].txt %>
How so?

2021-02-25 00:19 UTC, mbarnett commented on test/fixtures/digitization/books.yml
> +  resource_type: <%= CONTROLLED_VOCABULARIES[:digitization][:resource_type].txt %>
To be slightly clearer, we could just modify the OpenStruct to let us look things up by key/label as well, eg something like

```ruby
    vocab.define_singleton_method(:to_uri) do |key|
      config[vocab_name][key]
    end
```
`in controlled_vocabularies.rb` and then 

```ruby
resource_type: <%= CONTROLLED_VOCABULARIES[:digitization][:resource_type].to_uri('Text') %>
```

The only area of concern here is the "I need to figure out" part, that I'm currently trying to figure out, which is how best to bridge the distinction between different kinds of vocabs (URI->symbol->text indirectly via locale vs URI->text directly), because the text labels are going to not work as method names for the OpenStruct

2021-03-10 17:46 UTC, pgwillia commented on db/migrate/20201204210653_add_folk_fest_attributes_to_digitization_book.rb
> +      t.extent has_predicate: ::TERMS[:rdau].extent
This is the same as
```suggestion
      t.extent has_predicate: ::RDF::Vocab::RDAU.P60550.properties[:'http://metadataregistry.org/uri/profile/regap/lexicalAlias']
```
I decided to go with adding this to our TERMS hash so that it's clear what we're talking about.

Another thing I tried was to add accessors for the lexicalAliases in an initializer but wasn't successful.  

```
# config/initializers/rdau_vocabulary.rb
require 'rdf/vocab'

class RDF::Vocab::RDAU
  RDF::Vocab::RDAU.properties.each do |property|\n",
    next unless property.properties[:'http://metadataregistry.org/uri/profile/regap/lexicalAlias']
    define_singleton_method property.properties[:'http://metadataregistry.org/uri/profile/regap/lexicalAlias'].qname.last do
      property.properties[:'http://metadataregistry.org/uri/profile/regap/lexicalAlias']
    end
  end
end
```

With the goal of being able to invoke `RDF::Vocab::RDAU.send(:'extent.en')` and get "http://rdaregistry.info/Elements/u/extent.en"

2021-03-10 22:20 UTC, mbarnett approved these changes
This looks really good to me! Do you want to tackle the UI (nothing fancy needed right now, just really basic) or start looking at ingesting real data, as a next step?

2021-03-10 22:42 UTC, pgwillia commented on config/terms.yml
> +    extent: extent.en
I just looked back at the FolkFestTriples - v.1' and the Data Dictionary.  The URI as specified was 'http://rdaregistry.info/Elements/u/P60550'

```suggestion
    extent: P60550
```

2021-03-10 22:56 UTC, mbarnett approved these changes

2021-03-10 22:59 UTC, merged