Labels for active facet badges
ualbertalib/jupiter pull request #2115
Opened 2021-01-25 19:03 UTC by pgwillia

# Context
Applied Filters could show more information. Such as the facet they belong to.  Currently active facets are jumbled together.

Related to #1261

## What's New

Before:
![image](https://user-images.githubusercontent.com/1220762/105752879-15ca8080-5f05-11eb-8c27-4dd54df3320d.png)

After:
![image](https://user-images.githubusercontent.com/1220762/105753060-53c7a480-5f05-11eb-97c2-8f270a36174a.png)

Remember to request a reviewer when you submit!

2021-01-25 19:27 UTC, pgwillia commented on app/views/application/_facet_result.html.erb
> +          <% if do_header %>
We only want the label to appear once for the active facet.

2021-01-25 20:24 UTC, murny commented on app/views/application/_facet_result.html.erb
> +            <label class="font-size: 75%"><%= facet_result.category_name %>:</label>
Some tiny comments on UI/UX:

![image](https://user-images.githubusercontent.com/1930474/105760391-f9334600-5f0e-11eb-885c-0d866f9ed2dd.png)

- Seems very congested? Probably needs some spacing between facets with something like `ml-3`  (aka `margin-left: 1rem`) or maybe just putting each facet on a separate line? Not sure. Curious what others do (Since we use Newegg as an example in the story, They make, each facet and values is in its own container, so visually its all contained and separated) .
- Not sure if `<label>` is the right HTML element to use (typically you use label with a `for=` attribute to associate it with something like an input tag)? I'd probably just use a `header` or a some text tag instead and nest the `badge` span within it. So if you look at official docs (https://getbootstrap.com/docs/4.6/components/badge/#example), the badges are inside a typography tag (So ours might look like this instead `<h4>Subject/Keyword<span class="badge badge-secondary">Cat</span><span class="badge badge-secondary">Dog</span></h4>`)
- Don't think `class="font-size: 75%"` is valid attribute/html? You probably thinking of `style="font-size: 75%"` instead. However we should be using inline css for styling. I think using a header/typograph element would help with this or look into some font/typograph helpers from bootstrap

Overall though, nice work. Big improvement 👍

2021-01-25 20:28 UTC, murny commented on app/views/application/_facet_result.html.erb
> +          <% if do_header %>
Makes sense. Be nice if we can find a different way to do this instead of using this `flag` but I'm drawing a blank 🤔

2021-01-25 21:27 UTC, pgwillia commented on app/views/application/_facet_result.html.erb
> +            <label class="font-size: 75%"><%= facet_result.category_name %>:</label>
Thanks for the comments.
How about using `p class="h6"`?
![image](https://user-images.githubusercontent.com/1220762/105768283-677d0600-5f19-11eb-8635-3001868bb772.png)

2021-01-25 21:44 UTC, murny commented on app/views/application/_facet_result.html.erb
> +            <label class="font-size: 75%"><%= facet_result.category_name %>:</label>
Yeah that looks much better 🎉. Looks pretty good to me for MVP 👍

2021-01-25 21:51 UTC, murny commented on app/views/application/_facet_result.html.erb
> +          <% if do_header %>
Yeah it's almost like we should ditch the `content_for` stuff and just re-render this html in the facet badges area. Sure your duplicating code, but you will have much better control of it and wouldn't need this `do_header flag`

But this might be out of scope as it will be a bit of a refactor. Curious if Matt has any other ideas to improve this

2021-01-25 22:06 UTC, mbarnett commented on app/views/application/_facet_result.html.erb
> +            <label class="font-size: 75%"><%= facet_result.category_name %>:</label>
IDK, I feel like this eats up too much vertical space. What about folding the category into the label? Something like

<img width="857" alt="Screen Shot 2021-01-25 at 3 06 02 PM" src="https://user-images.githubusercontent.com/51773/105772062-dd37a080-5f1e-11eb-8ff9-7a7bdbabef63.png">

Would also be worth reaching out to Sarah to discuss, since she might have some ideas around this for Digitization

2021-01-25 22:07 UTC, mbarnett commented on app/views/application/_facet_result.html.erb
> +            <label class="font-size: 75%"><%= facet_result.category_name %>:</label>
(would want to have "short-forms" of facets eg) "author" instead of the full category "Author / Creator / Contributor"

2021-01-25 22:11 UTC, murny commented on app/views/application/_facet_result.html.erb
> +            <label class="font-size: 75%"><%= facet_result.category_name %>:</label>
I like this  👍. If we did this too then we wouldn't need the `do_header` flag and all that logic that goes with it. As we can just repeat each category with the value. And is probably much closer to what you find in the wild (other ecommerce sites). Code is simpler and looks better (Sure category name is repeated but that's okay)

2021-01-25 22:13 UTC, murny commented on app/views/application/_facet_result.html.erb
> +            <label class="font-size: 75%"><%= facet_result.category_name %>:</label>
Yeah heres an example that does this solution: 
![image](https://user-images.githubusercontent.com/1930474/105772770-ed9c4b00-5f1f-11eb-99bf-86a2eead52c9.png)

2021-01-27 22:39 UTC, pgwillia commented on app/helpers/search_helper.rb
> +  def short_category_name(category_name)
Added a helper to compute the short form.  This is pretty crude.  Maybe we want to be able to specify in the locales instead?

2021-01-27 22:41 UTC, mbarnett commented on app/helpers/search_helper.rb
> +  def short_category_name(category_name)
Yeah my first thought is that locales is the right place for this

2021-01-28 00:16 UTC, pgwillia commented on app/helpers/search_helper.rb
> +  def short_category_name(category_name)
Fixed using locales!

2021-01-28 01:25 UTC, murny approved these changes
Looks really good 👍. Very nice work 🎉

2021-01-28 18:32 UTC, mbarnett requested changes
Ok, two more things: this should be merging to integration, not master, and we need to feature flag this off so that we can potentially merge integration and cut a release without deploying this universally

2021-01-29 22:06 UTC, pgwillia commented
- [x] feature flags
- [x] integration branch

2021-01-29 22:16 UTC, murny submitted a review, later dismissed
🎉

2021-02-04 00:02 UTC, mbarnett requested changes
Looks good overall, just a couple of suggestions for making the approach a bit cleaner.

Would also be good to add a couple of tests to check that facets are doing the right thing with/without the flag flipped?

2021-02-04 00:02 UTC, mbarnett commented on app/views/application/_facet_result.html.erb
> +              <% end %>
Suggest putting this logic in the Decorator instead (since containing logic that otherwise has to live in the view is basically what it's there for). Right now `display` here just calls `DefaultFacetDecorator.display` or one of its many overrides in the subclasses in `app/decorators/facets/`, so the simplest way to do this would probably be something like doing `<%= present(facet_value).display_facet_value %>` (or some other method name), add that method to `DefaultFacetDecorator` only, with something like:

```ruby
def display_facet_value
  if Flipper.enabled?(:facet_badge_category_name)
    "{facet_value.short_category_name}: #{display}"
  else
    display
  end
end
```

This way we keep the same logic of kicking display to the customized subclasses, but hide the logic here.

2021-02-04 00:02 UTC, mbarnett commented on app/views/application/_range_facet_result.html.erb
> +          <% end %>
Same basic suggestion as above.

2021-02-04 00:08 UTC, mbarnett commented on app/views/application/_facet_result.html.erb
> +              <% end %>
(if you're feeling up to the extra refactoring, it might make more sense to rename the existing `display` method in DefaultFacetDecorator and all of the subclassses to something like `display_value` and then call what I called `display_facet_value` above, `display`. Then the views can keep calling `%= present(facet_value).display %>` and the method name in the base class and subclasses is arguably closer to what it actually is)

2021-02-05 22:55 UTC, mbarnett approved these changes
Looks good, just one small question about the method name

2021-02-05 22:55 UTC, mbarnett commented on app/models/jupiter_core/solr_services/range_facet_result.rb
> +  alias value humanized_range
Any reason not to go the extra step and just rename the `humanized_range` method? I don't remember if it has any other uses offhand

2021-02-05 23:20 UTC, pgwillia commented on app/models/jupiter_core/solr_services/range_facet_result.rb
> +  alias value humanized_range
No any other uses.  That makes too much sense 👍

2021-02-25 00:22 UTC, mbarnett commented on app/helpers/presenters_helper.rb
> +       obj.is_a?(JupiterCore::SolrServices::RangeFacetResult)
Ok, this is the last bit of feedback, promise: can you add a TODO here to figure out a better way to do this, eg) introduce a facet superclass or something, so that we don't keep pilling on more kinds of things to check for in the future?

2021-02-25 18:03 UTC, mbarnett approved these changes

2021-02-25 18:29 UTC, mbarnett approved these changes

2021-02-25 18:36 UTC, merged