Default behaviour within a facet to 'OR'
ualbertalib/jupiter pull request #2116
Opened 2021-01-25 19:15 UTC by pgwillia

## Context

As a user, I would like to be able to select multiple options in the author facet category, and
I would like the search logic to be "OR", so I can select same author with the variation (Jane Doe or J. Doe or Jane M. Doe etc)

Related to #1990

## What's New

The default behaviour within a facet is to 'OR'

2021-01-25 19:26 UTC, pgwillia commented on app/models/jupiter_core/search.rb
> +      fq << %Q(#{key}:\(#{values.collect { |value| "\"#{value}\"" }.join(' ')}\))
https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-BooleanOperatorsSupportedbytheStandardQueryParser

The default is OR so having the terms joined by a space will accomplish this.  Alternately these could be joined by ' OR' with the same result.

2021-01-25 19:26 UTC, pgwillia commented on test/fixtures/items.yml
> +practical:
Wanted another `VISIBILITY_PUBLIC` that I could use to demonstrate OR functionality.

2021-01-25 19:26 UTC, pgwillia commented on test/integration/sitemap_test.rb
> +    assert_select 'url', count: 5
Adding the extra fixture bumps this count.

2021-01-25 22:15 UTC, mbarnett commented
Would be worth maybe setting up a meeting with Sarah to discuss the whole context of this, because I don't know off-hand if this is desirable behaviour for the Digitization work, and if it isn't then we need to do something more sophisticated then just a blanket change of the search semantics for everything?

2021-01-25 22:24 UTC, pgwillia commented
> Would be worth maybe setting up a meeting with Sarah to discuss the whole context of this, because I don't know off-hand if this is desirable behaviour for the Digitization work, and if it isn't then we need to do something more sophisticated then just a blanket change of the search semantics for everything?

I'll set up that conversation.

2021-01-25 22:25 UTC, mbarnett commented
Thanks!

2021-01-28 18:34 UTC, mbarnett requested changes
carrying over observations from other PR: integration/feature flags good

2021-01-29 22:05 UTC, pgwillia commented
- [x] feature flags
- [x] integration branch

2021-01-29 22:18 UTC, murny approved these changes
Looks really good! Nice work 👍

2021-02-03 23:40 UTC, mbarnett requested changes
This looks really good, I just have a couple of small suggestions about readability and catching a possible issue with another test

2021-02-03 23:40 UTC, mbarnett commented on app/models/jupiter_core/search.rb
> +        fq << %Q(#{key}:\(#{values.collect { |value| "\"#{value}\"" }.join(' ')}\))
This is super pedantic, but can we join them with an explicit OR rather than just a space? I know the end result is the same, but it might be a bit clearer to the reader (me) who will inevitably forget what meaning a space has in Solr query syntax.

2021-02-03 23:40 UTC, mbarnett commented on test/models/search_test.rb
> +  end
This is very close to "test that the universe is sane" but, since we've added the codepath switch, can you do a second test to verify that when the flipper flag is disabled we get Original Flavor search results? Just so we can have some assurance that a change someone is testing against one codepath doesn't inadvertently leak into or otherwise break the other?

2021-02-05 22:58 UTC, mbarnett approved these changes
![Pretty Good!](https://i.giphy.com/media/l1J9O9elEvuRjMyXu/giphy.gif?cid=ecf05e47zvih29kzkfdvd3zlw0yj5y2lpbr6fv4afe6w40pm&rid=giphy.gif)

2021-02-05 23:33 UTC, merged