WIP Use markdown to style some of our descriptions
ualbertalib/jupiter pull request #2239
Opened 2021-03-16 21:00 UTC by pgwillia

## Context

Many "description" or "abstract" fields (at the Item level as well as Communities and Collections) contain HTML tags. Because these are text fields, HTML is not rendered in the UI and text looks garbled and it's way less readable than ideal.

Markdown should work really well for this since that's already used in many of the tools staff working in repositories are familiar with.

Related to #1322
Replaces #2230

## What's New
- Added the redcarpet gem because it basically does what we want with markdown.  
- add `markdown` decorator
- updated SolrExporters to use the new `strip_markdown` helper to remove content being indexed

## To Do
* raw descriptions should appear in edit forms (not decorated)
* search results are truncated.  Should either match tags despite truncation or strip tags
* Faker markdown tables aren't parsed as tables by redcarpet

2021-03-19 21:14 UTC, pgwillia reviewed
There are a few things I'm stumped by.  Hopefully @mbarnett et al can offer some counsel.

Another thing I'm struggling with is un-decorating the values used in the simple form/ wizard.  Right now the value that is displayed is decorated.  We want the input field in the form to not be decorated by the preview to be decorated.  I can't wrap my head around where that should happen or how. https://github.com/ualbertalib/jupiter/blob/83b42712135ccf59e111e211ea176a10a60ad73a/app/views/items/draft/describe_item.html.erb#L90-L94

2021-03-19 21:14 UTC, pgwillia commented on app/views/collections/show.html.erb
> +      <p><%= @collection.decorate.description %></p>
I thought I decorated this in the controller, but it didn't seem to take.

2021-03-19 21:14 UTC, pgwillia commented on app/views/communities/_community.html.erb
> +      <p class="text-muted"><%= community.decorate.description %></p>
I thought I decorated this in the controller, but again it didn't seem to take.

2021-03-19 21:14 UTC, pgwillia commented on app/helpers/application_helper.rb
> +    truncate strip_tags(text), length: length, separator: separator, omission: omission
There are a couple of places where rendering the markdown doesn't make sense.  The meta description of the page and the truncated search results (where we can't ensure matching tags).

2021-03-19 22:35 UTC, mbarnett requested changes
This is definitely a better approach with the decorators, and I added some feedback about how we can conform to their suggestions a bit more idiomatically.

I'm not 100% sure what's going on with the Collection show page. We might need to hop on a call Monday if pry doesn't help you figure it out. I did figure out the issue with the community one though.

2021-03-19 22:35 UTC, mbarnett commented on app/views/application/_results.html.erb
> +              <%= render result.decorate, highlights: fulltext_hits %>
Hmm, this is a bit of a weird usecase versus "normal" ActiveRecord which Draper has some helpers for, and I think, after reviewing the Draper docs, that decorating it at the call to render the way you have is actually the best approach. Anything earlier forces us into iterating the collection multiple times, and runs counter to their recommendations in a lot of ways.

2021-03-19 22:35 UTC, mbarnett commented on app/controllers/communities_controller.rb
> +    @community = Community.find(params[:id]).decorate
In terms of establishing good patterns, I don't think this is quite what we want. Pulling from the Draper docs:

> 
> Decorators are supposed to behave very much like the models they decorate, and for that reason it is very tempting to just decorate your objects at the start of your controller action and then use the decorators throughout. Don't.
> 
> Because decorators are designed to be consumed by the view, you should only be accessing them there. Manipulate your models to get things ready, then decorate at the last minute, right before you render the view. This avoids many of the common pitfalls that arise from attempting to modify decorators (in particular, collection decorators) after creating them.
> 

What you've done absolutely works, but I think we'd benefit from doing things the way Draper recommends, to establish good decorator hygiene right away and not set ourselves up for future problems down the road. In this case that would look something like:

```ruby
    community = Community.find(params[:id])
    authorize community

    respond_to do |format|
      format.html do
        @collections = community.collections.order(Collection.sort_order(params)).page params[:page]
        @community = community.decorate
      end
      format.js do
        # Used for the collapsable dropdown to show member collections
        @collections = community.collections.order(Collection.sort_order(params))
        @community = community.decorate
      end

      format.json do
        # Used in item_draft.js
        collections = community.collections.order(title: :asc)
        collections = collections.select { |c| c.restricted.blank? } unless current_user&.admin?
        render json: community.decorate.attributes.merge(collections: collections)
      end
```

2021-03-19 22:35 UTC, mbarnett commented on app/views/collections/show.html.erb
> +      <p><%= @collection.decorate.description %></p>
Try sticking a `<% binding.pry %>` right above this, and see what `@collection` is? I show it as 

```ruby
[1] pry(#<#<Class:0x00007fd1eb26f9c0>>)> @collection
=> #<CollectionDecorator:0x00007fd1ac1c8420
 @_routes=nil,
 @context={},
 @object=
  #<Collection:0x00007fd1ac1c8a60
   id: "32157177-bbc8-4e1f-9a09-d4fbea62df
```

etc

2021-03-19 22:35 UTC, mbarnett commented on app/views/communities/_community.html.erb
> +      <p class="text-muted"><%= community.decorate.description %></p>
I think you missed this one in the controller, actually.

We're getting here via:

https://github.com/ualbertalib/jupiter/blob/7099d30cd11b8d06d96f6a713f8ec55ae52b49a5/app/views/communities/index.html.erb#L38

which means you needed to decorate the collection in `CommunityController#index` via the Draper helper methods for decorating collections of ActiveRecord objects.

2021-03-26 21:52 UTC, mbarnett requested changes
This is really good and getting really close, just a couple of notes about making things a wee bit more idiomatic, and making some names more guessable – and one concern about how we want items to look in search results?

2021-03-26 21:52 UTC, mbarnett commented on app/decorators/item_decorator.rb
> +  def plain_description
Maybe "raw" would be more descriptive than "plain"? Or "unrendered" or something?

2021-03-26 21:52 UTC, mbarnett commented on app/decorators/community_decorator.rb
> +  end
I'm wondering if there's any reason you can think of not to hoist this up into `ApplicationDecorator`? It seems like a generic solution for all such decorators so I'm thinking we could just make it the default, because I can't think of anything obvious it might break.

2021-03-26 21:52 UTC, mbarnett commented on app/views/application/_item.html.erb
> +        <%= render(highlights) || jupiter_truncate(item.plain_description) %>
Don't we want rendered markdown here? I'm thinking that this going to lead to some funky looking search results with various raw markdown characters in them?

2021-03-26 21:52 UTC, mbarnett commented on app/decorators/item_decorator.rb
> +  def plain_description
Further thinking about this, and the `preview_markdown` in Draft*, I'm thinking it would be nice if these were a clear antonym pair, for discoverability? `unrendered_` here and `rendered_` in the Drafts? (or cooked/raw, but that's more of a stretch and less clear?)

2021-03-26 21:52 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +  options = {
Generally speaking, you don't want to do variables like this directly in the class scope – the semantics are kind of funky, eg) someone will come along and try to do:

```ruby
def foo
   renderer.blah
end
```

and then discover it's not in-scope for anything. The more usual approach is to do it as a method returning the value, or just in this case, make it a constant.

2021-03-26 21:52 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +  RenderMarkdown = Redcarpet::Markdown.new(renderer, Rails.configuration.markdown_rendering_extensions)
The ClassCase'd constants here are a bit odd (I think it's just an artifact of the refactorings you've already done?), because these aren't really classes or modules. 

You *could* switch it to constant case – MARKDOWN_RENDERER – but I think a more idiomatic solution in Ruby here is to put this all in memoized methods:

```ruby
private
def html_renderer
  @@html_renderer ||= Redcarpet::Render::HTML.new(options)
end

def markdown_renderer(text)
   @@markdown_renderer ||= Redcarpet::Markdown.new(html_renderer, Rails.configuration.markdown_rendering_extensions)
end
```

etc, and then call those in your public methods.

2021-03-26 22:04 UTC, pgwillia commented on app/decorators/community_decorator.rb
> +  end
The only reason I can think of is that the collections of Communities are the only one that needs it right now.  Making it the default collection decorator does make sense but is it a premature optimization?

2021-03-26 22:14 UTC, pgwillia commented on app/views/application/_item.html.erb
> +        <%= render(highlights) || jupiter_truncate(item.plain_description) %>
Yeah, I can see what you mean here about names.  We've got rendered, raw and stripped versions of description.  In the Drafts* we want the default description to be raw and the special case to be the rendered version.  In the other cases we want the default description to be the rendered version and the special case to be the stripped version (`plain_description`) here.

2021-03-26 22:16 UTC, pgwillia commented on app/views/application/_item.html.erb
> +        <%= render(highlights) || jupiter_truncate(item.plain_description) %>
This is a special case because of the truncation.  We can't guarantee that the tags will match when the rendered description is truncated.  This would cause some bizarre artifacts in the search results and in the meta page description.

2021-03-26 22:18 UTC, mbarnett commented on app/decorators/community_decorator.rb
> +  end
So (to kind of explain what's going on in my head when I see this kind of thing) philosophically I'd draw a distinction between:

a premature optimization – where optimization usually means "making the code really inscrutable and weird because it happens to be faster that way" – being bad because you're degrading the quality of the code but don't actually have the numbers in front of you _proving_ that the performance cost is important enough to offset the readability and understandability cost

and _this_, which we wouldn't be doing for optimization purposes but for what I'm going to call "thinking like a more Senior Developer-y reasons". 

Basically the observation here is that PaginatingDecorator works for all classes, so any Decorator for a collection of a class that needs to be decorated will *at some point* need to add this same method with the same contents. Our job as more Senior people in the codebase is to think ahead and say "well, what I don't want to have happen here is for someone who's maybe a bit newer or more junior to try to figure out how to do this, look at how it's already done, and then copy-and-paste this method into their Decorator to get it to work, and carry on, because that wouldn't be very DRY". 

We can preempt that by making all Decorators behave this way by default, without the loss of readability you'd see in a premature optimization. We're really just thinking ahead and making things more ergonomic for everybody, and it's always good to build your APIs such that they make it effortless for your team to do the right thing with them from the start, whereas this way we're requiring the _next_ person to do the bit of work to solve their problem the right way.

2021-03-26 22:23 UTC, mbarnett commented on app/views/application/_item.html.erb
> +        <%= render(highlights) || jupiter_truncate(item.plain_description) %>
Yeah, I missed this the first time around but we don't want to truncate in the middle of a tag, but we ALSO don't want to expose the user to un-rendered markdown just to avoid that.

I think what we want here is either to strip the text, so that it renders plainly without tags to worry about truncating, but doesn't have any weird markdown appearing on the page, or we want to do HTML-aware truncation, where we render the description and then are more careful about how we cut the text. (probably the first way is fine, here, because the second version adds some overhead as you have to parse your own generated HTML just to generate more HTML)

2021-04-09 16:41 UTC, murny commented on app/controllers/collections_controller.rb
> +    @community = Community.find(params[:community_id]).decorate
Do you need to decorate this twice? Here and on Line 17. Probably can just remove this one?

2021-04-09 18:34 UTC, pgwillia commented on app/controllers/collections_controller.rb
> +    @community = Community.find(params[:community_id]).decorate
Good catch.  I'll remove!

2021-04-22 20:52 UTC, mbarnett requested changes
Just a few really small nits at this point, but otherwise looks great!

2021-04-22 20:52 UTC, mbarnett commented on app/models/exporters/solr/base_exporter.rb
> +  def self.unrender_markdown(text)
Nit: Rendering markdown means taking markdown and producing HTML, so this doesn't really *unrender* markdown (which implies taking HTML and turning it back into markdown), it just removes the markup, right?

2021-04-22 20:52 UTC, mbarnett commented on db/seeds.rb
> +      description: if idx == THINGS.size-1
Tiny Tiny Nit: there should be spaces around the `-` operator. Surprised Rubocop doesn't, of all things, enforce this.

2021-04-22 20:52 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +  def unrender_markdown(text)
See the naming nit on the Solr exporter.

2021-04-22 20:52 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
These aren't set to `require: false` in the Gemfile, so Bundler automatically requires them at Application boot. You don't need to separately require them here.

2021-04-22 21:50 UTC, pgwillia commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Why do I get `NameError: uninitialized constant Redcarpet::Render::StripDown` in the tests if I remove these?

2021-04-22 21:54 UTC, pgwillia commented on app/models/exporters/solr/base_exporter.rb
> +  def self.unrender_markdown(text)
I was trying to get antonym pairs (in this case render/unrender) as we discussed before.  The challenge is still that we want rendered/raw/stripped versions of the text.  If I change this back to `strip_markdown` does it make sense?

2021-04-22 22:00 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
That's odd, I specifically pulled this branch down to make sure I was right that this was unnecessary – and I just double-checked that this is passing. 

This is a long shot, but maybe Spring's the issue? You could try doing `bin/spring stop` before re-running the tests, after making this change.

2021-04-22 22:00 UTC, mbarnett commented on app/models/exporters/solr/base_exporter.rb
> +  def self.unrender_markdown(text)
I think so, or it makes more sense to me, anyways.

2021-04-22 22:04 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Just for reference:

```
$ bin/spring stop
Spring stopped.
$ rails c        
/Users/matt/.rbenv/versions/2.6.6/gemsets/jupiter/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
W, [2021-04-22T16:02:29.735234 #41113]  WARN -- Skylight: [SKYLIGHT] [4.3.2] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Running via Spring preloader in process 41140
Loading development environment (Rails 6.0.3.6)
irb(main):001:0> Redcarpet::Render::StripDown
=> Redcarpet::Render::StripDown
```

so it's definitely getting required at boot, for me.

2021-04-22 22:10 UTC, pgwillia commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Stopping spring didn't help.  Restarting my machine didn't help.  Hmm.  Wondering what's going on there.

2021-04-22 22:12 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
What ruby version are you using?

Also is it possible that you have the gems locally but haven't bundled properly for some reason? (it should prevent you from doing that if the lockfile is stable, but...)

2021-04-22 22:15 UTC, pgwillia commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
```
$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

$ bundle info redcarpet
  * redcarpet (3.5.1)
        Summary: Markdown that smells nice
        Homepage: http://github.com/vmg/redcarpet
        Path: /home/pgwillia/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/redcarpet-3.5.1
```

2021-04-22 22:18 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
I'm using 2.6.6p146, let me try it with ruby 2.7...

2021-04-22 22:26 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Fresh installed 2.7.2p137 and completely rebundled:

```
irb(main):001:0> Redcarpet::Render::StripDown
=> Redcarpet::Render::StripDown
```

All tests green.

Try pushing the deletion up to this branch? Let's see what happens on CI.

2021-04-22 23:02 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Ok, I was able to re-create this with Ruby 3.0 and a brand new Rails 6.1 app. Unsure why I can't recreate this in the Jupiter directory.

Poking around the redcarpet gem, it looks like the main gem file doesn't require 'render_strip' by default, which probably explains your error, so you should be able to verify that deleting `require 'redcarpet'` works, because that is the main file and Bundler *does* require it by default (verified in the fresh 3.0 app).

Which leaves us with the optional 'redcarpet/render_strip'. My take is that the right way to this is to keep letting Bundler be the driver of all gem requires, rather than requiring things manually in random files. You can tell bundler to load extra files for you like this:

`gem 'redcarpet', require: ['redcarpet', 'redcarpet/render_strip']` 

(by default, it just infers that it should do `require 'redcarpet'` unless you manually tell it the file(s) to require).

2021-04-22 23:06 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Figured out the jupiter thing – if you look at my diff, I'd deleted the lines from application_decorator.rb but not base_exporter.rb, so 'render_strip' was getting pulled in during boot anyways, creating the confusion. Which kind of illustrates why centralizing requires in Bundler is less error prone I guess 😅

2021-04-23 00:59 UTC, pgwillia commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Nice!  Good sleuthing. From Java and C++ includes were pretty common so this ruby way is new to me.  Looks like it works!

2021-04-23 17:10 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +require 'redcarpet/render_strip'
Yeah, it works a bit differently than `import` in that there's no scope to it; once something in the process has `require`d a file, everything in it at the top level is visible globally, and not just in the one file that did the `require`. `#include` *kind of* works similarly in that the contents of the file you pull in are globally visible to the entire compilation unit, it's just that in C++ the compilation unit is (generally) a relatively small part of the program, whereas in Ruby the compilation unit effectively is the full program (nature of ahead-of-time compilation of individual files that are eventually linked together vs runtime dynamic languages, more or less)

2021-04-23 17:26 UTC, mbarnett reviewed
Last thing, I swear

2021-04-23 17:26 UTC, mbarnett commented on app/decorators/application_decorator.rb
> +  }.freeze
Sorry, I should have thought of this before: I know this is only used here, but can we haul this over to `config/application.rb`? Just so everything that controls what's allowed is centralized in one spot.

2021-04-23 19:50 UTC, pgwillia commented on app/decorators/application_decorator.rb
> +  }.freeze
Done.  This makes sense after moving the other part.

2021-04-23 20:07 UTC, mbarnett approved these changes
![giphy](https://user-images.githubusercontent.com/51773/115924598-325f5180-a43d-11eb-84fd-e7dea72c5ac1.gif)

2021-04-23 20:11 UTC, merged