bring_back_invalid_date_filtering_flash
ualbertalib/jupiter pull request #2558
Opened 2021-10-13 19:58 UTC by ConnorSheremeta

Bring back the flash message if the filtering dates are invalid (like when the begin date is after the end date.)

2021-10-13 20:06 UTC, murny commented on test/integration/search_invalid_date_range_test.rb
> +  test 'search with invalid date range shows alert' do
Two suggestions here. Do we need an integration test to test this? Or can we use a controller test? As it's not really doing an "Integration" (in the sense of testing multiple things or a workflow)

Regardless of if using an integration test or not,  we should group this test with another search integration test, instead of having a different file for each test

2021-10-13 21:07 UTC, pgwillia commented on app/controllers/search_controller.rb
> +    flash.now[:alert] = t('search.invalid_date_range_flash') if search_query_index.invalid_date_range
This used to be set
https://github.com/ualbertalib/jupiter/blob/fb8cca3af9f3016d16581a4f4e95ca1fd5cd7e1b/app/services/user_search_service.rb#L63-L70
Before the errors there were fixed.

What is the advantage of moving where we set the error to the controller?

2021-10-13 21:08 UTC, pgwillia commented on app/controllers/search_controller.rb
> +    flash.now[:alert] = t('search.invalid_date_range_flash') if search_query_index.invalid_date_range
Good thinking moving this to the locales!

2021-10-13 21:14 UTC, ConnorSheremeta commented on app/controllers/search_controller.rb
> +    flash.now[:alert] = t('search.invalid_date_range_flash') if search_query_index.invalid_date_range
When calling flash[:alert] inside of the service an error was thrown. Not sure if this is from something recent or if it has always been this way but it's fixed now.

2021-10-29 20:41 UTC, pgwillia approved these changes

2021-10-29 20:42 UTC, pgwillia requested changes
LGTM!  Just a nit about the Changelog

2021-10-29 20:42 UTC, pgwillia commented on CHANGELOG.md
> +- Bring back illogical date range faceting flash message [#2030](https://github.com/ualbertalib/jupiter/issues/2030)
This should be up in the unreleased section.

2022-01-12 21:58 UTC, pgwillia approved these changes
![](https://media.giphy.com/media/3o6Zt7mutmbv76m0ko/giphy.gif)

2022-01-13 22:11 UTC, merged