Cds/reduce assertions per test
ualbertalib/jupiter pull request #2563
Opened 2021-10-15 17:24 UTC by ConnorSheremeta

Some of them could not be reduced as it would make the test less comprehensive.

2021-10-29 20:39 UTC, pgwillia requested changes
This is good stuff!  I have a concern about further relaxing the Max Minitest/MultipleAssertions, a nit about the Changelog, some concerns about assertions that seem to be missing, and some suggestions.

2021-10-29 20:39 UTC, pgwillia commented on test/services/statistics_test.rb
> -      assert_equal [1, 0], Statistics.for(item_id: obj_id)
Looks like we're not exercising `Statistics.for` anymore?

2021-10-29 20:39 UTC, pgwillia commented on test/services/statistics_test.rb
> +  test 'view counts increment correctly' do
I like how you broke this up into view and download.  What do you think about breaking each of these up further?
- testing two increments in the same time period
- testing after expiring the key

2021-10-29 20:39 UTC, pgwillia commented on test/system/admin_communities_index_test.rb
> +  end
Smart way to break this up!  This is [one of the problem tests](https://github.com/ualbertalib/jupiter/issues/2129#issuecomment-905744278).  Perhaps this will reduce it's flakiness!

2021-10-29 20:39 UTC, pgwillia commented on test/system/collections_pagination_and_sort_test.rb
> -    assert_selector 'ul.list-group li:nth-child(9) a', text: 'Fancy Collection 08'
Did something happen to the second last item?

2021-10-29 20:39 UTC, pgwillia commented on test/system/collections_pagination_and_sort_test.rb
> -    assert_selector 'ul.list-group li:nth-child(9) a', text: 'Fancy Collection 02'
Why not test this?

2021-10-29 20:39 UTC, pgwillia commented on test/system/collections_pagination_and_sort_test.rb
> +  end
Yass!  This is so much better in organization, description and size of tests.

2021-10-29 20:39 UTC, pgwillia commented on test/system/search_test.rb
> +  test 'anybody should be able to view search results' do
This is great.  Another big improvement.  Hopefully will help with the slow tests too.

2021-10-29 20:57 UTC, murny commented on .rubocop.yml
> +  Max: 35 # default 3
Think 15 is a good default. If your over 15 expectations then you should be asking yourself why and if you can do this better.

But we shouldn't strive to get this down to 10 or 5 or.....the default of 3. There could easily be valid reasons to write tests with 10 expectations. A good integration test testing a complicated workflow would easily get close to 10 expectations and this is probably more then fine.

Think the key is keeping code readable and maintainable for the right reasons and not just cause an arbitrary linter rule is telling you to break your code into smaller chunks (which could make it far less readable or maintainable) for no real reason other then we have to keep it under a magic number. (It's the same reason why we disabled MethodLength, ClassLength, BlockLength, etc for similar reasons)

2021-10-29 21:46 UTC, pgwillia commented on .rubocop.yml
> +  Max: 35 # default 3
:100:  Good default, readable/maintainable code and testing the right things.

2023-02-13 18:32 UTC, pgwillia requested changes
This is looking good! I have a question about the job test directory.

2023-03-06 20:51 UTC, pgwillia approved these changes
![](https://media.giphy.com/media/RJzv5gG13bFsER317k/giphy.gif)

2023-03-06 21:57 UTC, merged