Accommodate template changes new batch ingest - Multi-file upload
ualbertalib/jupiter pull request #2945
Opened 2022-08-17 16:05 UTC by lagoan

## Context

The new batch ingest workflow requires the ability to specify multiple files per item row as it was possible in the previous command line batch ingest workflow.

Related to #2943, #2853

## What's New

Changes in the code include:
+ Accept multiple files on batch ingest job with separated with the '|' character
+ Validation for multiple files added through the interface split by the '|' character
+ Tests to check multiple files can be handled by the batch ingestion

2022-08-24 23:02 UTC, pgwillia requested changes
Looking good!  I checked the recordings for secrets and don't see any.  Thank you for the code comments explaining the method for creating the cassettes.  

My main concern is around error handling and edge conditions.  I didn't see a test for validation failure.  Once we think that through I think this is ready to go!

2022-08-26 16:51 UTC, lagoan commented on test/jobs/batch_ingestion_job_test.rb
> +        VCR.use_cassette('google_fetch_spreadsheet_multiple_files_in_one_row',
I will take a look into this, it would definitely make for cleaner code.

2022-08-26 17:18 UTC, lagoan commented on app/jobs/batch_ingestion_job.rb
> +    return unless files.any?
This was just meant to stop the rest of the code if there were no files added from the beggining. I agree that it ins't clear.

2022-08-26 17:23 UTC, lagoan commented on app/jobs/batch_ingestion_job.rb
> +      files << google_credentials.download_file(item_file.google_file_id, item_file.google_file_name)
You are righ, the resulting Tempfiles would still be referenced and stored in memory. I will change it back to ingest each file seperatedly.

2022-08-26 17:33 UTC, lagoan commented on app/jobs/batch_ingestion_job.rb
> +      files << google_credentials.download_file(item_file.google_file_id, item_file.google_file_name)
It looks like Tempfiles are only stored on the disk. Regardless, with the exception of a couple of tests, all files are ingested individually. I will continue with this behaviour.

2022-08-29 18:37 UTC, pgwillia requested changes
I think we're just missing a test of the change to the validator?

https://github.com/ualbertalib/jupiter/blob/09f318b0c6b6996116ebcaa1d33cfc3205468a8f/test/models/batch_ingest_test.rb#L67-L91

Could edit this so that it has two files missing?
https://github.com/ualbertalib/jupiter/blob/09f318b0c6b6996116ebcaa1d33cfc3205468a8f/test/vcr/google_fetch_spreadsheet.yml#L87-L110

i.e. `"conference_logo.png | conference.pdf"`

Then add to the batch_ingest_test.rb from above
```
assert_equal("File(s) 'conference_logo.png, conference.pdf' from row 1 of spreadsheet are not listed in the file list below", 
                     batch_ingest.errors[:google_spreadsheet_id].fourth)
```

2022-08-30 20:27 UTC, pgwillia approved these changes
![](https://media.giphy.com/media/l41lUjUgLLwWrz20w/giphy.gif)

2022-08-31 16:30 UTC, merged