Change/accomodate template changes new batch ingest template headers
ualbertalib/jupiter pull request #2957
Opened 2022-08-30 20:05 UTC by lagoan

## Context

We are changing the spreadsheet headers from the new batch ingest workflow to match the variable names used in jupiter to represent the model

Related to #2853 , #2941

## What's New

+ Changes in batch ingest job to get the data from differently named columns.
+ Changes to the range of data fetched from the spreadsheet
+ Changes in validation to make sure the data is there.

The changed headers are:

| Old header | New header |
| --------------- | -----------------|
| alternate_title | alternative_title |
| type	 | item_type |
| owner_id | removed |
| subjects | subject |
| date_created | created |
| places | spatial_subjects |
| time_periods | temporal_subjects |
| citations | is_version_of |
| related_item | related_link |
| license_text | rights |

2022-08-31 21:55 UTC, pgwillia requested changes
Looks good!  Seems like a pretty straightforward replacement of the headers you mention.  I think we could document the change to using `User.first` as the owner for any items ingested this way.

2022-08-31 21:55 UTC, pgwillia commented on app/jobs/batch_ingestion_job.rb
> +      unlocked_obj.owner = User.first
Could we add a comment documenting this decision?

2022-08-31 21:55 UTC, pgwillia commented on app/services/google_drive_client_service.rb
> +    range = "'Data'!A:W"
It took me a moment to figure out why this change.  I realized it's because we removed the owner column.

2022-09-01 15:48 UTC, lagoan commented on app/services/google_drive_client_service.rb
> +    range = "'Data'!A:W"
Yes, wanted to only fetch the data we needed as we were doing before this change.

2022-09-01 15:55 UTC, pgwillia commented on app/jobs/batch_ingestion_job.rb
> +      unlocked_obj.owner = User.first
I can see the decision documented in the commit history.  Maybe a comment in the code isn't needed.

2022-09-01 15:55 UTC, pgwillia approved these changes

2022-09-01 16:17 UTC, lagoan commented on app/jobs/batch_ingestion_job.rb
> +      unlocked_obj.owner = User.first
It won't hurt to have it.

2022-09-02 16:41 UTC, pgwillia approved these changes

2022-09-02 17:47 UTC, merged